export const courseList = [
  {
    id: "1",
    title: "React로 시작하는 프론트엔드 입문",
    description: "React 기초부터 실전 프로젝트까지 한 번에!",
    content:
      "JSX, 컴포넌트, 상태관리, 라우팅 등 프론트엔드의 핵심을 단계별로 학습합니다.",
    thumbnailUrl: "/images/course/react1.jpg",
    instructor: "김코딩",
    category: ["테크", "프로그래밍", "프론트엔드"],
    level: "입문",
    tags: ["프론트엔드", "입문"],
    reviews: [{ rating: 5 }, { rating: 4.5 }, { rating: 5 }],
    studentCount: 320,
    createdAt: "2025-10-01T00:00:00Z",
  },
  {
    id: "2",
    title: "실무에서 바로 쓰는 Figma UI 디자인",
    description: "UI/UX 기초부터 실무 디자인 시스템까지!",
    content:
      "Figma 툴 활용법, 컴포넌트 설계, UI 패턴, 협업 워크플로우를 배웁니다.",
    thumbnailUrl: "/images/course/figma.jpg",
    instructor: "이디자인",
    category: ["테크", "디자인", "UX/UI 디자인"],
    level: "초급",
    tags: ["UX/UI 디자인", "초급"],
    reviews: [{ rating: 4.5 }, { rating: 4.2 }],
    studentCount: 150,
    createdAt: "2025-09-15T00:00:00Z",
  },
  {
    id: "3",
    title: "Python으로 데이터 분석 시작하기",
    description: "Pandas, Numpy로 배우는 데이터 분석",
    content: "기초 문법부터 실전 데이터 전처리와 시각화까지 진행합니다.",
    thumbnailUrl: "/images/course/python-data.jpg",
    instructor: "박데이터",
    category: ["테크", "데이터사이언스", "데이터 분석"],
    level: "초급",
    tags: ["데이터 분석", "초급"],
    reviews: [{ rating: 3.8 }, { rating: 4.0 }],
    studentCount: 210,
    createdAt: "2025-08-20T00:00:00Z",
  },
  {
    id: "4",
    title: "ChatGPT로 업무 자동화하기",
    description: "반복 업무를 AI로 자동화해보세요.",
    content: "프롬프트 설계, 자동화 워크플로우, Zapier 연동 등을 다룹니다.",
    thumbnailUrl: "/images/course/chatgpt-automation.jpg",
    instructor: "최AI",
    category: ["테크", "AI 스킬업", "ChatGPT"],
    level: "입문",
    tags: ["ChatGPT", "입문"],
    reviews: [{ rating: 5 }, { rating: 4.9 }, { rating: 5 }],
    studentCount: 540,
    createdAt: "2025-07-30T00:00:00Z",
  },
  {
    id: "5",
    title: "기초 드로잉 클래스",
    description: "연필 한 자루로 시작하는 그림의 세계",
    content: "기초 선 긋기부터 명암 표현, 인물화 기초를 배웁니다.",
    thumbnailUrl: "/images/course/drawing.jpg",
    instructor: "김작가",
    category: ["크리에이티브", "드로잉", "기초 드로잉"],
    level: "입문",
    tags: ["기초 드로잉", "입문"],
    reviews: [{ rating: 4.0 }, { rating: 4.1 }],
    studentCount: 110,
    createdAt: "2025-09-01T00:00:00Z",
  },
  {
    id: "6",
    title: "주식 ETF로 자산 키우기",
    description: "투자 기초부터 ETF 포트폴리오 전략까지",
    content: "초보 투자자를 위한 ETF 상품 이해와 실전 운용 전략을 배웁니다.",
    thumbnailUrl: "/images/course/etf.jpg",
    instructor: "박투자",
    category: ["커리어", "금융·재테크", "주식·ETF"],
    level: "초급",
    tags: ["주식·ETF", "초급"],
    reviews: [{ rating: 3.2 }, { rating: 3.5 }],
    studentCount: 400,
    createdAt: "2025-06-12T00:00:00Z",
  },
  {
    id: "7",
    title: "AI를 활용한 마케팅 자동화",
    description: "AI와 함께 SNS 마케팅 효율을 높이기",
    content: "자동 포스팅, 광고 성과 분석, 고객 세분화를 실습합니다.",
    thumbnailUrl: "/images/course/marketing-ai.jpg",
    instructor: "정마케팅",
    category: ["테크", "마케팅", "디지털 마케팅"],
    level: "중급",
    tags: ["디지털 마케팅", "중급"],
    reviews: [{ rating: 4.2 }],
    studentCount: 180,
    createdAt: "2025-05-10T00:00:00Z",
  },
  {
    id: "8",
    title: "웹 백엔드 입문: Node.js로 시작하기",
    description: "서버 기초와 REST API 설계 실습",
    content: "Node.js와 Express를 이용해 간단한 API 서버를 만들어봅니다.",
    thumbnailUrl: "/images/course/node-backend.jpg",
    instructor: "박백엔드",
    category: ["테크", "프로그래밍", "백엔드"],
    level: "입문",
    tags: ["백엔드", "입문"],
    reviews: [{ rating: 4.8 }, { rating: 4.9 }],
    studentCount: 260,
    createdAt: "2025-07-01T00:00:00Z",
  },
  {
    id: "9",
    title: "스페인어 회화 마스터",
    description: "여행에서 바로 쓸 수 있는 스페인어 표현",
    content: "기초 문법, 발음, 일상 회화를 상황별로 배웁니다.",
    thumbnailUrl: "/images/course/spanish.jpg",
    instructor: "로사",
    category: ["언어", "제2 외국어", "스페인어"],
    level: "입문",
    tags: ["스페인어", "입문"],
    reviews: [{ rating: 4.7 }],
    studentCount: 330,
    createdAt: "2025-09-10T00:00:00Z",
  },
  {
    id: "10",
    title: "토익 900+ 목표 달성 비법",
    description: "단기간 점수 상승을 위한 실전 전략",
    content: "LC/RC 집중 공략, 파트별 공략법, 기출문제 분석",
    thumbnailUrl: "/images/course/toeic.jpg",
    instructor: "토익쌤",
    category: ["언어", "외국어 시험", "토익"],
    level: "중급",
    tags: ["토익", "중급"],
    reviews: [{ rating: 4.6 }, { rating: 4.7 }],
    studentCount: 420,
    createdAt: "2025-08-25T00:00:00Z",
  },
  {
    id: "11",
    title: "모바일 앱 개발 실전: React Native",
    description: "단 하나의 코드로 iOS/Android 동시 개발",
    content: "React Native를 활용한 앱 제작, 배포까지 실습합니다.",
    thumbnailUrl: "/images/course/react-native.jpg",
    instructor: "한풀스택",
    category: ["테크", "프로그래밍", "모바일 앱"],
    level: "중급",
    tags: ["모바일 앱", "중급"],
    reviews: [{ rating: 4.9 }, { rating: 4.8 }],
    studentCount: 370,
    createdAt: "2025-09-05T00:00:00Z",
  },
  {
    id: "12",
    title: "Vue.js로 만드는 SPA 웹앱",
    description: "Vue 3 Composition API로 SPA 구조를 이해하기",
    content: "라우터, 상태관리, 컴포넌트 통신을 중심으로 실습합니다.",
    thumbnailUrl: "/images/course/vue.jpg",
    instructor: "오프론트",
    category: ["테크", "프로그래밍", "프론트엔드"],
    level: "중급",
    tags: ["Vue.js", "중급"],
    reviews: [{ rating: 4.4 }, { rating: 4.7 }],
    studentCount: 250,
    createdAt: "2025-10-05T00:00:00Z",
  },
  {
    id: "13",
    title: "데이터 시각화 with Tableau",
    description: "데이터로 스토리텔링하는 법 배우기",
    content: "Tableau를 활용해 시각적 인사이트를 도출합니다.",
    thumbnailUrl: "/images/course/tableau.jpg",
    instructor: "박데이터",
    category: ["테크", "데이터사이언스", "시각화"],
    level: "초급",
    tags: ["Tableau", "데이터 시각화"],
    reviews: [{ rating: 4.3 }],
    studentCount: 180,
    createdAt: "2025-09-25T00:00:00Z",
  },
  {
    id: "14",
    title: "Next.js 풀스택 개발 가이드",
    description: "React 개발자를 위한 서버 사이드 렌더링 입문",
    content:
      "Next.js로 SSR, SSG, API 라우트를 배우며 풀스택 개발을 경험합니다.",
    thumbnailUrl: "/images/course/nextjs.jpg",
    instructor: "김코딩",
    category: ["테크", "프로그래밍", "풀스택"],
    level: "고급",
    tags: ["Next.js", "풀스택"],
    reviews: [{ rating: 4.9 }, { rating: 5 }],
    studentCount: 310,
    createdAt: "2025-09-28T00:00:00Z",
  },
  {
    id: "15",
    title: "Adobe Premiere Pro 영상 편집 마스터",
    description: "촬영부터 편집, 컬러 보정까지 한 번에!",
    content: "Premiere Pro의 핵심 기능과 실전 편집 노하우를 배웁니다.",
    thumbnailUrl: "/images/course/premiere.jpg",
    instructor: "이디자인",
    category: ["크리에이티브", "사진·영상", "영상 편집"],
    level: "초급",
    tags: ["영상 편집", "초급"],
    reviews: [{ rating: 4.5 }],
    studentCount: 240,
    createdAt: "2025-09-22T00:00:00Z",
  },
  {
    id: "16",
    title: "SQL로 데이터 다루기",
    description: "데이터 분석의 기본기, SQL 완전 정복",
    content: "SELECT, JOIN, GROUP BY 등 실무 쿼리 작성법을 익힙니다.",
    thumbnailUrl: "/images/course/sql.jpg",
    instructor: "박데이터",
    category: ["테크", "데이터사이언스", "데이터 분석"],
    level: "입문",
    tags: ["SQL", "입문"],
    reviews: [{ rating: 4.6 }],
    studentCount: 200,
    createdAt: "2025-09-18T00:00:00Z",
  },
  {
    id: "17",
    title: "블렌더 3D 모델링 입문",
    description: "3D 공간에서 상상력을 현실로!",
    content: "Blender 기본 조작부터 캐릭터 모델링까지 실습합니다.",
    thumbnailUrl: "/images/course/blender.jpg",
    instructor: "김작가",
    category: ["크리에이티브", "3D·모션그래픽", "Blender"],
    level: "입문",
    tags: ["Blender", "입문"],
    reviews: [{ rating: 4.2 }],
    studentCount: 150,
    createdAt: "2025-08-30T00:00:00Z",
  },
  {
    id: "18",
    title: "비즈니스 이메일 영어 작성법",
    description: "글로벌 업무에서 통하는 이메일 문장 패턴",
    content: "메일 구조, 어투, 표현을 상황별로 학습합니다.",
    thumbnailUrl: "/images/course/business-english.jpg",
    instructor: "로사",
    category: ["언어", "비즈니스 영어", "영어 회화"],
    level: "초급",
    tags: ["비즈니스 영어", "초급"],
    reviews: [{ rating: 4.8 }],
    studentCount: 310,
    createdAt: "2025-09-08T00:00:00Z",
  },
  {
    id: "19",
    title: "Notion으로 일잘러 되는 법",
    description: "생산성과 협업 효율을 높이는 Notion 활용",
    content: "데이터베이스, 템플릿, 자동화 세팅을 배웁니다.",
    thumbnailUrl: "/images/course/notion.jpg",
    instructor: "최AI",
    category: ["커리어", "생산성", "협업 툴"],
    level: "입문",
    tags: ["Notion", "입문"],
    reviews: [{ rating: 4.4 }],
    studentCount: 430,
    createdAt: "2025-10-10T00:00:00Z",
  },
  {
    id: "20",
    title: "HTML/CSS로 웹페이지 만들기",
    description: "기초부터 반응형 페이지 제작까지",
    content: "Flex, Grid, Media Query를 활용한 실습 중심 강의",
    thumbnailUrl: "/images/course/htmlcss.jpg",
    instructor: "오프론트",
    category: ["테크", "프로그래밍", "프론트엔드"],
    level: "입문",
    tags: ["HTML", "CSS", "입문"],
    reviews: [{ rating: 4.7 }],
    studentCount: 500,
    createdAt: "2025-09-20T00:00:00Z",
  },
  {
    id: "21",
    title: "Git & GitHub 협업 마스터",
    description: "개발 협업의 필수 스킬, 버전 관리 완전 정복",
    content: "브랜치 전략, PR, 리베이스를 실습합니다.",
    thumbnailUrl: "/images/course/git.jpg",
    instructor: "한풀스택",
    category: ["테크", "개발도구", "협업"],
    level: "초급",
    tags: ["Git", "협업"],
    reviews: [{ rating: 4.8 }],
    studentCount: 290,
    createdAt: "2025-08-15T00:00:00Z",
  },
  {
    id: "22",
    title: "AWS 클라우드 입문",
    description: "AWS 서비스 구조와 배포 개념 익히기",
    content: "EC2, S3, Lambda 등 주요 서비스 실습 포함",
    thumbnailUrl: "/images/course/aws.jpg",
    instructor: "박백엔드",
    category: ["테크", "클라우드", "AWS"],
    level: "초급",
    tags: ["AWS", "클라우드"],
    reviews: [{ rating: 4.5 }],
    studentCount: 210,
    createdAt: "2025-08-05T00:00:00Z",
  },
  {
    id: "23",
    title: "Django로 만드는 웹 서비스",
    description: "파이썬 백엔드 프레임워크 완전 정복",
    content: "ORM, 템플릿, REST API를 이용한 실전 예제 중심",
    thumbnailUrl: "/images/course/django.jpg",
    instructor: "박백엔드",
    category: ["테크", "프로그래밍", "백엔드"],
    level: "중급",
    tags: ["Django", "중급"],
    reviews: [{ rating: 4.6 }],
    studentCount: 240,
    createdAt: "2025-09-12T00:00:00Z",
  },
  {
    id: "24",
    title: "디지털 드로잉: 캐릭터 일러스트",
    description: "아이패드로 감성 일러스트 그리기",
    content: "프로크리에이트 도구와 채색 테크닉을 배웁니다.",
    thumbnailUrl: "/images/course/illustration.jpg",
    instructor: "김작가",
    category: ["크리에이티브", "디지털 드로잉", "일러스트"],
    level: "초급",
    tags: ["디지털 드로잉", "초급"],
    reviews: [{ rating: 4.3 }],
    studentCount: 170,
    createdAt: "2025-09-02T00:00:00Z",
  },

  {
    id: "31",
    title: "Swift로 배우는 iOS 앱 개발",
    description: "iPhone 앱 제작의 기본부터 실전까지",
    content:
      "SwiftUI를 활용한 인터페이스 구성, 데이터 관리, 앱 스토어 배포를 다룹니다.",
    thumbnailUrl: "/images/course/swift.jpg",
    instructor: "한풀스택",
    category: ["테크", "프로그래밍", "모바일 앱"],
    level: "중급",
    tags: ["Swift", "iOS"],
    reviews: [{ rating: 4.7 }, { rating: 4.8 }],
    studentCount: 260,
    createdAt: "2025-10-16T00:00:00Z",
  },
  {
    id: "25",
    title: "Excel로 업무 자동화하기",
    description: "함수, 매크로, 피벗테이블로 생산성 향상",
    content: "자동화 스크립트로 반복 업무를 줄이는 실습 중심 강의입니다.",
    thumbnailUrl: "/images/course/excel.jpg",
    instructor: "정마케팅",
    category: ["커리어", "생산성", "오피스"],
    level: "초급",
    tags: ["Excel", "자동화"],
    reviews: [{ rating: 4.4 }, { rating: 4.5 }],
    studentCount: 520,
    createdAt: "2025-10-12T00:00:00Z",
  },
  {
    id: "26",
    title: "Kotlin으로 안드로이드 앱 개발",
    description: "모던 안드로이드 개발 흐름 이해",
    content: "Jetpack, MVVM, 코루틴을 활용한 앱 개발을 실습합니다.",
    thumbnailUrl: "/images/course/kotlin.jpg",
    instructor: "한풀스택",
    category: ["테크", "프로그래밍", "모바일 앱"],
    level: "중급",
    tags: ["Kotlin", "Android"],
    reviews: [{ rating: 4.7 }, { rating: 4.8 }],
    studentCount: 230,
    createdAt: "2025-09-27T00:00:00Z",
  },
  {
    id: "27",
    title: "데이터 엔지니어링 파이프라인 구축",
    description: "실무형 ETL과 데이터 파이프라인 구축하기",
    content: "Airflow, Spark, 데이터 웨어하우징 개념을 실습 중심으로 다룹니다.",
    thumbnailUrl: "/images/course/data-eng.jpg",
    instructor: "박데이터",
    category: ["테크", "데이터사이언스", "데이터 엔지니어링"],
    level: "고급",
    tags: ["Airflow", "Spark"],
    reviews: [{ rating: 4.6 }, { rating: 4.7 }],
    studentCount: 160,
    createdAt: "2025-09-30T00:00:00Z",
  },
  {
    id: "28",
    title: "개발자를 위한 수학 리마스터",
    description: "선형대수·확률로 강화하는 문제 해결력",
    content: "코딩 테스트와 머신러닝 기초에 필요한 수학 개념을 정리합니다.",
    thumbnailUrl: "/images/course/math.jpg",
    instructor: "최AI",
    category: ["테크", "컴퓨터사이언스", "수학"],
    level: "중급",
    tags: ["선형대수", "확률"],
    reviews: [{ rating: 4.5 }],
    studentCount: 140,
    createdAt: "2025-08-28T00:00:00Z",
  },
  {
    id: "29",
    title: "포트폴리오를 위한 브랜딩 디자인",
    description: "콘셉트부터 결과물까지 브랜딩 실습",
    content: "타이포그래피, 컬러 시스템, 목업 제작을 통해 브랜딩을 완성합니다.",
    thumbnailUrl: "/images/course/branding.jpg",
    instructor: "이디자인",
    category: ["크리에이티브", "브랜딩", "그래픽 디자인"],
    level: "중급",
    tags: ["브랜딩", "그래픽"],
    reviews: [{ rating: 4.6 }],
    studentCount: 190,
    createdAt: "2025-09-14T00:00:00Z",
  },
  {
    id: "30",
    title: "시니어를 위한 커리어 리부트",
    description: "업스킬·리스킬로 커리어 전환 준비",
    content: "자기분석, 로드맵 설계, 포트폴리오 준비 과정을 안내합니다.",
    thumbnailUrl: "/images/course/career-reboot.jpg",
    instructor: "박투자",
    category: ["커리어", "커리어전환", "자기계발"],
    level: "입문",
    tags: ["커리어전환", "입문"],
    reviews: [{ rating: 4.2 }],
    studentCount: 125,
    createdAt: "2025-10-15T00:00:00Z",
  },
  {
    id: "32",
    title: "UI 애니메이션 with After Effects",
    description: "모션을 입힌 인터랙티브 UI 디자인",
    content:
      "AE를 활용한 마이크로 인터랙션, UX 트랜지션 모션 디자인을 배웁니다.",
    thumbnailUrl: "/images/course/aftereffects.jpg",
    instructor: "이디자인",
    category: ["크리에이티브", "모션그래픽", "UI 애니메이션"],
    level: "중급",
    tags: ["After Effects", "UI 모션"],
    reviews: [{ rating: 4.6 }],
    studentCount: 190,
    createdAt: "2025-10-13T00:00:00Z",
  },
  {
    id: "33",
    title: "AI 이미지 생성 실습: Midjourney & DALL·E",
    description: "AI로 창작물 만들기, 기획부터 출력까지",
    content:
      "프롬프트 엔지니어링, 스타일 제어, 결과물 리터칭 실습 중심으로 진행합니다.",
    thumbnailUrl: "/images/course/ai-image.jpg",
    instructor: "최AI",
    category: ["테크", "AI 스킬업", "이미지 생성"],
    level: "입문",
    tags: ["AI 이미지", "프롬프트"],
    reviews: [{ rating: 4.9 }],
    studentCount: 420,
    createdAt: "2025-10-14T00:00:00Z",
  },
  {
    id: "34",
    title: "인스타그램 콘텐츠 기획과 제작",
    description: "팔리는 콘텐츠의 비밀, 기획부터 운영까지",
    content: "브랜드 스토리텔링, 피드 디자인, 해시태그 전략을 배웁니다.",
    thumbnailUrl: "/images/course/instagram.jpg",
    instructor: "정마케팅",
    category: ["커리어", "마케팅", "SNS 콘텐츠"],
    level: "초급",
    tags: ["SNS", "콘텐츠 기획"],
    reviews: [{ rating: 4.4 }],
    studentCount: 370,
    createdAt: "2025-09-30T00:00:00Z",
  },
  {
    id: "35",
    title: "R로 배우는 통계 데이터 분석",
    description: "데이터 사이언스를 위한 통계 기초",
    content: "R 언어 문법, 데이터 처리, 시각화까지 전 과정을 다룹니다.",
    thumbnailUrl: "/images/course/r-data.jpg",
    instructor: "박데이터",
    category: ["테크", "데이터사이언스", "통계 분석"],
    level: "중급",
    tags: ["R", "통계"],
    reviews: [{ rating: 4.5 }],
    studentCount: 180,
    createdAt: "2025-10-02T00:00:00Z",
  },
  {
    id: "36",
    title: "영어 프레젠테이션 완성하기",
    description: "비즈니스 발표를 위한 말하기 실전 연습",
    content: "발음, 억양, 스토리 구성, 슬라이드 표현 등 실무 중심 학습입니다.",
    thumbnailUrl: "/images/course/presentation.jpg",
    instructor: "로사",
    category: ["언어", "비즈니스 영어", "프레젠테이션"],
    level: "중급",
    tags: ["영어 발표", "비즈니스 영어"],
    reviews: [{ rating: 4.8 }],
    studentCount: 290,
    createdAt: "2025-10-05T00:00:00Z",
  },
  {
    id: "37",
    title: "Notion x Slack 팀 협업 자동화",
    description: "팀 생산성을 높이는 워크플로우 통합",
    content: "Notion API와 Slack Webhook을 활용해 자동화 시스템을 구축합니다.",
    thumbnailUrl: "/images/course/slack-notion.jpg",
    instructor: "최AI",
    category: ["커리어", "생산성", "협업 툴"],
    level: "중급",
    tags: ["Notion", "Slack", "자동화"],
    reviews: [{ rating: 4.7 }],
    studentCount: 310,
    createdAt: "2025-10-11T00:00:00Z",
  },
  {
    id: "38",
    title: "C 언어로 배우는 프로그래밍 기초",
    description: "코딩 사고력 향상을 위한 입문 강의",
    content: "변수, 반복문, 배열, 포인터까지 기본 문법을 차근차근 다룹니다.",
    thumbnailUrl: "/images/course/c-language.jpg",
    instructor: "김코딩",
    category: ["테크", "프로그래밍", "기초"],
    level: "입문",
    tags: ["C언어", "입문"],
    reviews: [{ rating: 4.3 }],
    studentCount: 220,
    createdAt: "2025-09-22T00:00:00Z",
  },
  {
    id: "39",
    title: "포토샵으로 나만의 포스터 만들기",
    description: "기초부터 감각적인 디자인 실습까지",
    content: "레이어, 마스크, 브러시, 텍스트 디자인 활용법을 배웁니다.",
    thumbnailUrl: "/images/course/photoshop.jpg",
    instructor: "이디자인",
    category: ["크리에이티브", "그래픽 디자인", "포토샵"],
    level: "입문",
    tags: ["포토샵", "입문"],
    reviews: [{ rating: 4.5 }],
    studentCount: 260,
    createdAt: "2025-10-08T00:00:00Z",
  },
  {
    id: "40",
    title: "스타트업 창업 전략 A to Z",
    description: "아이디어 발굴부터 투자 유치까지의 여정",
    content: "비즈니스 모델 수립, 고객 검증, 피치덱 작성 실습을 포함합니다.",
    thumbnailUrl: "/images/course/startup.jpg",
    instructor: "박투자",
    category: ["커리어", "창업", "비즈니스"],
    level: "고급",
    tags: ["창업", "비즈니스"],
    reviews: [{ rating: 4.9 }],
    studentCount: 180,
    createdAt: "2025-10-17T00:00:00Z",
  },
];
